{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "k8s-notifier.fullname" . }}
  labels: {{- include "k8s-notifier.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "k8s-notifier.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "k8s-notifier.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
