name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          key: test-stable
      - run: cargo build --all-targets
      - run: cargo test
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: ./.github/actions/setup
        with:
          key: lint
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets -- -D warnings
